export interface IconPreset {
  id: string;
  name: string;
  category: string;
  iconUrl: string;
  defaultPort?: number;
  keywords: string[];
}

const CDN_BASE = 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg';

export const ICON_PRESETS: IconPreset[] = [
  // Media & Streaming
  {
    id: 'jellyfin',
    name: 'Jellyfin',
    category: 'Media',
    iconUrl: `${CDN_BASE}/jellyfin.svg`,
    defaultPort: 8096,
    keywords: ['media', 'movies', 'tv', 'streaming', 'video'],
  },
  {
    id: 'plex',
    name: 'Plex',
    category: 'Media',
    iconUrl: `${CDN_BASE}/plex.svg`,
    defaultPort: 32400,
    keywords: ['media', 'movies', 'tv', 'streaming'],
  },
  {
    id: 'emby',
    name: 'Emby',
    category: 'Media',
    iconUrl: `${CDN_BASE}/emby.svg`,
    defaultPort: 8096,
    keywords: ['media', 'movies', 'tv'],
  },
  {
    id: 'seerr',
    name: 'Overseerr / Jellyseerr',
    category: 'Media',
    iconUrl: `${CDN_BASE}/overseerr.svg`,
    defaultPort: 5055,
    keywords: ['requests', 'seerr', 'jellyseerr', 'overseerr', 'media'],
  },
  {
    id: 'audiobookshelf',
    name: 'Audiobookshelf / Pelagica',
    category: 'Media',
    iconUrl: `${CDN_BASE}/audiobookshelf.svg`,
    defaultPort: 8002,
    keywords: ['audiobooks', 'podcasts', 'pelagica', 'books'],
  },
  {
    id: 'navidrome',
    name: 'Navidrome',
    category: 'Media',
    iconUrl: `${CDN_BASE}/navidrome.svg`,
    defaultPort: 4533,
    keywords: ['music', 'audio', 'streaming'],
  },
  {
    id: 'photoprism',
    name: 'PhotoPrism',
    category: 'Media',
    iconUrl: `${CDN_BASE}/photoprism.svg`,
    defaultPort: 2342,
    keywords: ['photos', 'gallery', 'images'],
  },
  {
    id: 'immich',
    name: 'Immich',
    category: 'Media',
    iconUrl: `${CDN_BASE}/immich.svg`,
    defaultPort: 2283,
    keywords: ['photos', 'backup', 'gallery'],
  },

  // Downloads & Automation
  {
    id: 'radarr',
    name: 'Radarr',
    category: 'Downloads',
    iconUrl: `${CDN_BASE}/radarr.svg`,
    defaultPort: 7878,
    keywords: ['movies', 'downloads', 'arr', 'torrents'],
  },
  {
    id: 'sonarr',
    name: 'Sonarr',
    category: 'Downloads',
    iconUrl: `${CDN_BASE}/sonarr.svg`,
    defaultPort: 8989,
    keywords: ['tv', 'shows', 'downloads', 'arr', 'torrents'],
  },
  {
    id: 'prowlarr',
    name: 'Prowlarr',
    category: 'Downloads',
    iconUrl: `${CDN_BASE}/prowlarr.svg`,
    defaultPort: 9696,
    keywords: ['indexer', 'torrent', 'usenet', 'arr'],
  },
  {
    id: 'bazarr',
    name: 'Bazarr',
    category: 'Downloads',
    iconUrl: `${CDN_BASE}/bazarr.svg`,
    defaultPort: 6767,
    keywords: ['subtitles', 'arr', 'media'],
  },
  {
    id: 'lidarr',
    name: 'Lidarr',
    category: 'Downloads',
    iconUrl: `${CDN_BASE}/lidarr.svg`,
    defaultPort: 8686,
    keywords: ['music', 'downloads', 'arr'],
  },
  {
    id: 'readarr',
    name: 'Readarr',
    category: 'Downloads',
    iconUrl: `${CDN_BASE}/readarr.svg`,
    defaultPort: 8787,
    keywords: ['books', 'ebooks', 'arr'],
  },
  {
    id: 'qbittorrent',
    name: 'qBittorrent',
    category: 'Downloads',
    iconUrl: `${CDN_BASE}/qbittorrent.svg`,
    defaultPort: 8081,
    keywords: ['torrent', 'client', 'download', 'p2p'],
  },
  {
    id: 'transmission',
    name: 'Transmission',
    category: 'Downloads',
    iconUrl: `${CDN_BASE}/transmission.svg`,
    defaultPort: 9091,
    keywords: ['torrent', 'client', 'p2p'],
  },
  {
    id: 'sabnzbd',
    name: 'SABnzbd',
    category: 'Downloads',
    iconUrl: `${CDN_BASE}/sabnzbd.svg`,
    defaultPort: 8080,
    keywords: ['usenet', 'nzb', 'download'],
  },
  {
    id: 'recyclarr',
    name: 'Recyclarr / Cleanuparr',
    category: 'Downloads',
    iconUrl: `${CDN_BASE}/recyclarr.svg`,
    defaultPort: 11011,
    keywords: ['cleanup', 'trash', 'sync', 'cleanuparr'],
  },
  {
    id: 'flaresolverr',
    name: 'FlareSolverr / Trawl',
    category: 'Downloads',
    iconUrl: `${CDN_BASE}/flaresolverr.svg`,
    defaultPort: 8191,
    keywords: ['proxy', 'cloudflare', 'trawl', 'captcha'],
  },

  // Smart Home & Automation
  {
    id: 'home-assistant',
    name: 'Home Assistant',
    category: 'Automation',
    iconUrl: `${CDN_BASE}/home-assistant.svg`,
    defaultPort: 8123,
    keywords: ['iot', 'smarthome', 'hass', 'homeassistant', 'automation'],
  },
  {
    id: 'zigbee2mqtt',
    name: 'Zigbee2MQTT',
    category: 'Automation',
    iconUrl: `${CDN_BASE}/zigbee2mqtt.svg`,
    defaultPort: 8080,
    keywords: ['zigbee', 'mqtt', 'iot'],
  },
  {
    id: 'nodered',
    name: 'Node-RED',
    category: 'Automation',
    iconUrl: `${CDN_BASE}/node-red.svg`,
    defaultPort: 1880,
    keywords: ['automation', 'flows', 'iot'],
  },
  {
    id: 'mosquitto',
    name: 'Mosquitto MQTT',
    category: 'Automation',
    iconUrl: `${CDN_BASE}/mosquitto.svg`,
    defaultPort: 1883,
    keywords: ['mqtt', 'broker', 'iot'],
  },

  // System & Management
  {
    id: 'casaos',
    name: 'CasaOS',
    category: 'System',
    iconUrl: `${CDN_BASE}/casaos.svg`,
    defaultPort: 3000,
    keywords: ['dashboard', 'nas', 'os', 'server'],
  },
  {
    id: 'proxmox',
    name: 'Proxmox VE',
    category: 'System',
    iconUrl: `${CDN_BASE}/proxmox.svg`,
    defaultPort: 8006,
    keywords: ['hypervisor', 'vm', 'lxc', 'virtualization'],
  },
  {
    id: 'portainer',
    name: 'Portainer',
    category: 'System',
    iconUrl: `${CDN_BASE}/portainer.svg`,
    defaultPort: 9000,
    keywords: ['docker', 'containers', 'management'],
  },
  {
    id: 'dozzle',
    name: 'Dozzle',
    category: 'System',
    iconUrl: `${CDN_BASE}/dozzle.svg`,
    defaultPort: 8080,
    keywords: ['logs', 'docker', 'monitoring'],
  },
  {
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    category: 'System',
    iconUrl: `${CDN_BASE}/uptime-kuma.svg`,
    defaultPort: 3001,
    keywords: ['monitoring', 'status', 'uptime'],
  },
  {
    id: 'glances',
    name: 'Glances / Netdata',
    category: 'System',
    iconUrl: `${CDN_BASE}/glances.svg`,
    defaultPort: 61208,
    keywords: ['stats', 'system', 'monitoring', 'cpu'],
  },
  {
    id: 'grafana',
    name: 'Grafana',
    category: 'System',
    iconUrl: `${CDN_BASE}/grafana.svg`,
    defaultPort: 3000,
    keywords: ['metrics', 'dashboards', 'charts'],
  },
  {
    id: 'nginx-proxy-manager',
    name: 'Nginx Proxy Manager',
    category: 'System',
    iconUrl: `${CDN_BASE}/nginx-proxy-manager.svg`,
    defaultPort: 81,
    keywords: ['proxy', 'reverse proxy', 'ssl', 'nginx'],
  },
  {
    id: 'pihole',
    name: 'Pi-hole',
    category: 'System',
    iconUrl: `${CDN_BASE}/pi-hole.svg`,
    defaultPort: 80,
    keywords: ['dns', 'adblock', 'network'],
  },
  {
    id: 'adguard-home',
    name: 'AdGuard Home',
    category: 'System',
    iconUrl: `${CDN_BASE}/adguard-home.svg`,
    defaultPort: 3000,
    keywords: ['dns', 'adblock', 'privacy'],
  },
  {
    id: 'tailscale',
    name: 'Tailscale',
    category: 'System',
    iconUrl: `${CDN_BASE}/tailscale.svg`,
    keywords: ['vpn', 'mesh', 'network', 'wireguard'],
  },
  {
    id: 'gluetun',
    name: 'Gluetun VPN',
    category: 'System',
    iconUrl: `${CDN_BASE}/gluetun.svg`,
    keywords: ['vpn', 'wireguard', 'openvpn', 'privacy'],
  },

  // Productivity & Tools
  {
    id: 'vscode',
    name: 'VS Code / Code-Server',
    category: 'Development',
    iconUrl: `${CDN_BASE}/visual-studio-code.svg`,
    defaultPort: 8443,
    keywords: ['code', 'ide', 'editor', 'developer', 'code-server'],
  },
  {
    id: 'zennotes',
    name: 'ZenNotes / Obsidian',
    category: 'Productivity',
    iconUrl: `${CDN_BASE}/obsidian.svg`,
    defaultPort: 8001,
    keywords: ['notes', 'markdown', 'wiki', 'zennotes'],
  },
  {
    id: 'vaultwarden',
    name: 'Vaultwarden / Bitwarden',
    category: 'Productivity',
    iconUrl: `${CDN_BASE}/vaultwarden.svg`,
    defaultPort: 80,
    keywords: ['passwords', 'security', 'vault'],
  },
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    category: 'Productivity',
    iconUrl: `${CDN_BASE}/nextcloud.svg`,
    defaultPort: 80,
    keywords: ['cloud', 'files', 'sync', 'storage'],
  },
  {
    id: 'paperless-ngx',
    name: 'Paperless-ngx',
    category: 'Productivity',
    iconUrl: `${CDN_BASE}/paperless-ngx.svg`,
    defaultPort: 8000,
    keywords: ['documents', 'ocr', 'pdf', 'archive'],
  },
  {
    id: 'it-tools',
    name: 'IT-Tools',
    category: 'Productivity',
    iconUrl: `${CDN_BASE}/it-tools.svg`,
    defaultPort: 80,
    keywords: ['tools', 'developer', 'converter'],
  },
  {
    id: 'stirling-pdf',
    name: 'Stirling-PDF',
    category: 'Productivity',
    iconUrl: `${CDN_BASE}/stirling-pdf.svg`,
    defaultPort: 8080,
    keywords: ['pdf', 'editor', 'convert'],
  },

  // AI & LLMs
  {
    id: 'ollama',
    name: 'Ollama / LLM Wiki',
    category: 'AI & Tools',
    iconUrl: `${CDN_BASE}/ollama.svg`,
    defaultPort: 8080,
    keywords: ['ai', 'llm', 'wiki', 'ollama', 'llm-wiki-web'],
  },
  {
    id: 'open-webui',
    name: 'Open WebUI',
    category: 'AI & Tools',
    iconUrl: `${CDN_BASE}/open-webui.svg`,
    defaultPort: 8080,
    keywords: ['ai', 'chat', 'llm', 'gpt'],
  },
  {
    id: 'stable-diffusion',
    name: 'Automatic1111 / SD',
    category: 'AI & Tools',
    iconUrl: `${CDN_BASE}/automatic1111.svg`,
    defaultPort: 7860,
    keywords: ['ai', 'image', 'generation'],
  },
];
